[connections.gsheets]
# for a detailed tutorial on how to obtain these credentials see https://www.youtube.com/watch?v=HwxrXnYVIlU
spreadsheet = "<your-spreadsheet-url>"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet URL, when usign service_account it will be picked as folder_id
# type = "service_account"  # leave empty when using Public Spreadsheet URL, when using service_account -> type = "service_account"
project_id = "<your-project-id>"
private_key_id = "<your-private-key-id>"
private_key = "<your-private-key>"
client_email = "<your-client-email>"
client_id = "<your-client-id>"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "<your-client-x509-cert-url>"
